document.addEventListener('DOMContentLoaded',()=>{
 const q=s=>document.querySelector(s), qa=s=>document.querySelectorAll(s); const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches; const fine=matchMedia('(pointer:fine)').matches;
 const menu=q('#menu'), nav=q('#navlinks'); if(menu&&nav) menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
 qa('.navlinks a').forEach(a=>a.addEventListener('click',()=>nav?.classList.remove('open')));
 const progress=q('#progress'); addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?scrollY/max*100:0)+'%'},{passive:true});
 const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');obs.unobserve(e.target)}}),{threshold:.12}); qa('.reveal,.section-head,.about-card,.about-stats>div,.timeline article,.journey-grid article,.projects article,.cap-grid>div,.education article,.gallery figure,.article-grid a,.presence-grid a').forEach((el,i)=>{if(!el.classList.contains('reveal'))el.classList.add('reveal');el.style.transitionDelay=(i%5)*70+'ms';obs.observe(el)});
 if(fine&&!reduced){const orb=q('#cursorOrb');let x=innerWidth/2,y=innerHeight/2,tx=x,ty=y;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY;orb.style.opacity='1'},{passive:true});(function loop(){x+=(tx-x)*.12;y+=(ty-y)*.12;orb.style.left=x+'px';orb.style.top=y+'px';requestAnimationFrame(loop)})();
  const hero=q('.hero'),stage=q('#heroStage'),portrait=q('#portraitShell');let mx=0,my=0,cx=0,cy=0,px=0,py=0;hero.addEventListener('pointermove',e=>{const r=hero.getBoundingClientRect();mx=(e.clientX-r.left)/r.width-.5;my=(e.clientY-r.top)/r.height-.5},{passive:true});hero.addEventListener('pointerleave',()=>{mx=0;my=0});(function tick(){cx+=(mx*3.5-cx)*.045;cy+=(my*3-cy)*.045;px+=(mx*10-px)*.045;py+=(my*8-py)*.045;stage.style.transform=`translate3d(${px}px,${py}px,0)`;portrait.style.transform=`translate3d(${px*.35}px,${py*.35}px,0) rotate(${2+cx*.25}deg)`;requestAnimationFrame(tick)})();
  qa('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)/r.width*8,y=(e.clientY-r.top-r.height/2)/r.height*6;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
 }
 const year=q('#year');if(year)year.textContent=new Date().getFullYear();
});